- hosts: all
  gather_facts: no
  tasks:
  #  - name: Download installer zip
  #    get_url:
  #      url: http://myserver.domain.com/~ibmrepo/im/linux/agent.installer.linux.x86_64-latest.zip
  #      dest: /tmp/

  - name: Create IM directory
    file:
      state: directory
      path: /usr/local/WebSphere/Liberty

  - name: Unarchive installer zip
    unarchive:
      src: /tmp/wlp-javaee8-20.0.0.5.zip
      dest: /usr/local/WebSphere/Liberty
      remote_src: yes

  - name: Create
    profile_liberty:
      state: present 
      libertydir: /usr/local/WebSphere/Liberty/wlp
      name: server01
   
  - name: Start
    liberty_server:
      state: started 
      libertydir: /usr/local/WebSphere/Liberty/wlp
      name: server01
