- hosts: localhost
  connection: local
  tasks:
    - name: Download installer zip
      get_url:
        url: http://myserver.domain.com/~ibmrepo/im/linux/agent.installer.linux.x86_64-latest.zip
        dest: /tmp/

    - name: Create IM directory
      file:
        state: directory
        path: /tmp/im

    - name: Unarchive installer zip
      unarchive:
        src: /tmp/agent.installer.linux.x86_64-latest.zip
        dest: /tmp/im/

    - name: Install Installation Manager
      ibmim_installer:
        src: /tmp/im/
