#######################################################
# Libverty server provisioning playbook - RHEL7
#######################################################
- hosts: all
  gather_facts: no
  tasks:

  - name: Install unzip rpm
    yum:
      name: unzip
      state: present

  - name: Install ibm-java rpm
    yum:
      name: java
      state: present

  - name: Create Liberty install directory
    file:
      state: directory
      path: "{{ install_path }}"

  - name: Liberty Download and Unarchive zip
    unarchive:
      src: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/20.0.0.5/wlp-javaee8-20.0.0.5.zip
      dest: "{{ install_path }}"
      remote_src: yes

  - name: Create Liberty server
    profile_liberty:
      state: present 
      libertydir: "{{ install_path }}"/wlp
      name: "{{ server_name }}"

### configuration server.xml
  - name: Liberty server service IP setting
    shell: sed -i '28 i\                  host="{{ ansible_host }}"' "{{ install_path }}"/wlp/usr/servers/"{{ server_name }}"/server.xml

  - name: Liberty server service port(http) setting
    shell: sed -i 's/httpPort="9080"/httpPort="{{ http_port }}"/g' "{{ install_path }}"/wlp/usr/servers/"{{ server_name }}"/server.xml
 
  - name: Liberty server service port(https) setting
    shell: sed -i 's/httpsPort="9443"/httpsPort="{{ https_port }}"/g' "{{ install_path }}"/wlp/usr/servers/"{{ server_name }}"/server.xml

#  - name: Application Copy
#    copy:
#      src: "{{ app_name }}"
#      dest: "{{ install_path }}"/wlp/usr/servers/{{ server_name }}/apps

  - name: Liberty server Application deploy config setting - sample
    #shell: sed -i '34 i\    <application context-root="/" type="war" location="{{ app_name }}"/>' "{{ install_path }}"/wlp/usr/servers/"{{ server_name }}"/server.xml
    shell: sed -i '34 i\    <!--application context-root="/test" type="war" location="test"/-->' "{{ install_path }}"/wlp/usr/servers/"{{ server_name }}"/server.xml

  - name: Liberty server start
    liberty_server:
      state: started
      libertydir: "{{ install_path }}"/wlp
      name: "{{ server_name }}"
