- hosts: all
  gather_facts: no
  tasks:

 # - name: server start
 #   shell: /was/AppServer/wlp/bin/server start {{ server_name }} &
    
  - name: Start
    liberty_server:
      state: started
      libertydir: /was/AppServer/wlp
      name: "{{ server_name }}"
