- hosts: all
  gather_facts: no
  tasks:

  - name: server start
    shell: /was/AppServer/wlp/bin/server start {{ server_name }}

  - pause: seconds=10
 # - name: Start
 #   liberty_server:
 #     state: started
 #     libertydir: /was/AppServer/wlp
 #     name: "{{ server_name }}"
