- hosts: all
  gather_facts: no
  tasks:

  - name: Start
    liberty_server:
      state: started 
      libertydir: /was/AppServer/wlp/
      name: "{{ server_name }}"
    register: liberty
  - name: dsgg
    debug:
      msg: "{{ liberty.libertydir }}"
